[package]
name = "caledon"
version = "0.1.0"
authors = ["Steven Bosnick <sbosnick@sympatico.ca>"]
edition = "2018"
description = "Caledon is a Rust implemention of the Wayland protocol."
readme = "README.md"
repository = "https://github.com/sbosnick/caledon"
license = "MIT OR Apache-2.0"
categories = ["graphics", "gui", "rendering"]
keywords = ["wayland", "protocol"]

[dependencies]
tokio-util = { version = "0.3.1", features = ["codec"] }
thiserror = "1.0.19"
bytes = "0.5.4"

[dev-dependencies]
assert_matches = "1.3.0"
