// Copyright 2020 Steven Bosnick
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE-2.0 or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

use std::io::Write;

use crate::{model::Protocol, Error, Result};

pub fn generate_code<'a, W, I>(mut file: W, _protocols: I) -> Result<()>
where
    W: Write,
    I: Iterator<Item = &'a Protocol>,
{
    writeln!(file, "// File generated by caledon-build").map_err(Error::file_write)
}
