name: CI
on:
  pull_request:
  push:
    branches:
      - master

env:
  RUST_BACKTRACE: 1

jobs:

  test:
    name: Test ${{ matrix.rust }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.45.0

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Check Format
        if: matrix.rust == 'stable'
        uses: actions-rs/cargo@v1
        with:
            command: fmt
            args: -- --check

      - name: Clippy
        if: matrix.rust == 'stable'
        uses: actions-rs/clippy-check@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  # Test with at least one big endian target
  cross:
      name: Test Cross Compiled
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Install Rust Stable
          uses: actions-rs/toolchain@v1
          with:
              profile: minimal
              toolchain: stable
              target: powerpc-unknown-linux-gnu
              override: true

        - name: Test
          uses: actions-rs/cargo@v1
          with:
              command: test
              use-cross: true
              args: --target powerpc-unknown-linux-gnu
